### ISSUE TITLE
We need a unban Command....

### ISSUE THREAD

**Issue by xxoptikxx** [AmIrReZa386/FIREAC#10]
Hello,
i love this anticheat but it's really annoying to have to go into the server resources to unban someone. please give us a way to unban a player who was unfairly banned via /unban [banid].

Best regards, xxoptikkxx

**Comment by AmIrReZa386** [comment]
Hi xxoptikxx,

thanks for your suggestion i add a command soon ... 👍

**Comment by xxoptikxx** [comment]
thanks i love you :)

**Comment by AmIrReZa386** [comment]
Hi @xxoptikxx,

unban command add `/funban (Ban ID)`
you need to add your ids in `FIREAC\whitelists\fire-white.lua` in `UnBan` tables
if any problem in anti cheat and this command tell me there

thanks Amirreza Jaberi

**Comment by xxoptikxx** [comment]
is the update on github? because i dont have an idea how i can make this command😅

**Comment by AmIrReZa386** [comment]
Yes but don't download from release 

use this :
https://github.com/AmIrReZa386/FIREAC/archive/refs/heads/main.zip

**Comment by xxoptikxx** [comment]
[       script:FIREAC] FIREAC: Player Exilium Try For Join But | Ban ID:  #9937
> funban 9937
[    c-scripting-core] InvokeNative: execution failed: Argument at index 0 was null.
[       script:FIREAC] SCRIPT ERROR: Execution of native 00000000fee404f9 in script host failed: Argument at index 0 was null.
[       script:FIREAC] > GetPlayerEndpoint (GetPlayerEndpoint.lua:2)
[       script:FIREAC] > FIREAC_UNBANACCESS (@FIREAC/src/fire-server.lua:1120)
[       script:FIREAC] > ref (@FIREAC/src/fire-server.lua:1855)
> funban #9937
[    c-scripting-core] InvokeNative: execution failed: Argument at index 0 was null.
[       script:FIREAC] SCRIPT ERROR: Execution of native 00000000fee404f9 in script host failed: Argument at index 0 was null.
[       script:FIREAC] > GetPlayerEndpoint (GetPlayerEndpoint.lua:2)
[       script:FIREAC] > FIREAC_UNBANACCESS (@FIREAC/src/fire-server.lua:1120)
[       script:FIREAC] > ref (@FIREAC/src/fire-server.lua:1855)



this says my server console

**Comment by AmIrReZa386** [comment]
i check it again

**Comment by AmIrReZa386** [comment]
now fixed sorry for late

**Comment by xxoptikxx** [comment]
oke give me 10 minutes i check it

**Comment by xxoptikxx** [comment]
update its perfect i love it thank you

**Comment by AmIrReZa386** [comment]
Nice thanks for your suggestion
