### ISSUE TITLE
Anti Inject does not work

### ISSUE THREAD

**Issue by MaxYT12** [AmIrReZa386/FIREAC#11]
Hello, I think your anti-cheat is mega, but the anti-inject doesn't work, I'm told that the command doesn't exist, what can I do?

LG Max

**Comment by AmIrReZa386** [comment]
Hi,
I will update anti cheat to new fivem natives and this problem fix soon ..

**Comment by AmIrReZa386** [comment]
Hi @MaxYT12,

We updated some futures now mabey  some your problems fixed !
We add screen anti inject soon ...
I reopen this issues soon again

Thanks, Amirreza Jaberi
