### ISSUE TITLE
PLEASE HELP WITH THIS ERRO

### ISSUE THREAD

**Issue by johnkouk007** [AmIrReZa386/FIREAC#110]
[    script:AntiCheat] FIREAC: Player johnkouk007 Banned From Server | Reason:  Anti Superjump
[    script:AntiCheat] SCRIPT ERROR: @AntiCheat/src/fire-server.lua:2011: attempt to index a nil value (local 'Emoji')
[    script:AntiCheat] > FIREAC_MESSAGE (@AntiCheat/src/fire-server.lua:2011)
[    script:AntiCheat] > FIREAC_ACTION (@AntiCheat/src/fire-server.lua:1941)
[    script:AntiCheat] > handler (@AntiCheat/src/fire-server.lua:599)
[    script:AntiCheat] > rawQuery (@oxmysql/dist/build.js:26467)
[    script:AntiCheat] > processTicksAndRejections (node:internal/process/task_queues:96)

**Comment by AmirrezaJaberi** [comment]
This bug fixed in new version
