### ISSUE TITLE
Player is supposedly in god mode after bringing him

### ISSUE THREAD

**Issue by Zzeyy** [AmIrReZa386/FIREAC#18]
![image](https://user-images.githubusercontent.com/97387354/203809598-5ed067b4-9e4a-41e5-a37b-2bb8fff91fb9.png)

I've just bring the player and the AC immediately assumed the player has a god mode.

**Comment by Zzeyy** [comment]
![image](https://user-images.githubusercontent.com/97387354/203811531-ef14cd1d-c03e-42b5-8906-1494522caf5c.png)

**Comment by Zzeyy** [comment]
Overall, players are just getting targeted by the AC for no real reason.

**Comment by Zzeyy** [comment]
For example, carrying a person and driving a car makes the AC see that the player is using teleport hacks, when in fact the player does not teleport hack.

**Comment by AmIrReZa386** [comment]
Yes you are told good problem, i will check it

**Comment by Zzeyy** [comment]
And most importantly, don't make the warnings visible to players.
All of them were getting mad because of the anti cheat targeting them.

**Comment by AmIrReZa386** [comment]
Yes , it's good idea

**Comment by AmIrReZa386** [comment]
Hi,
check version 6.1.5
tell me if you have problem again

**Comment by TugaPowerROM** [comment]
still get anti teleport log issue ...

**Comment by TugaPowerROM** [comment]
altough it seems it only trigger when player is spawning on city

**Comment by TugaPowerROM** [comment]
For me it seems only trigger the teleport when the player its entering the city, then it wont trigger. Normal @AmIrReZa386 ?

**Comment by AmIrReZa386** [comment]
only teleport ?
godmode fixed ?

**Comment by AmIrReZa386** [comment]
> For me it seems only trigger the teleport when the player its entering the city, then it wont trigger. Normal @AmIrReZa386 ?

yes, but now i change spawn time for less miss ban 
thanks for report it
