### ISSUE TITLE
Ban

### ISSUE THREAD

**Issue by TugaPowerROM** [AmIrReZa386/FIREAC#20]
Although my ID its added to Admins and Unban list, if spawn something not allowed the FireAC will still ban although the ID it's over the withelist, normal behaviour? FireAC should not check if the person is Admin prior to ban/kick/warn?

**Comment by AmIrReZa386** [comment]
You put wrong ID
We test it on 2 server and it's fix

**Comment by TugaPowerROM** [comment]
```
WhiteList = {

}

Admins = {
    '221634362305******',                               	-- Discord ID
    'steam:11000010d******',                            	-- Steam Hex
    'license2:b5b0c0f8f472925c0e8b86752cae************', 	-- FiveM License
}

UnBan = {
    '221634362305******',                               	-- Discord ID
    'steam:11000010d******',                            	-- Steam Hex
    'license2:b5b0c0f8f472925c0e8b86752cae************', 	-- FiveM License
}
```

**Comment by TugaPowerROM** [comment]
And ID its fine because when spawn get the notification You Are Joined As Administrator !
