### ISSUE TITLE
List of bugs in 6.1.5

### ISSUE THREAD

**Issue by Zzeyy** [AmIrReZa386/FIREAC#21]
**Spelling Mistakes**

• `fire-config` Spelling mistake → `FIREAC.AntiSpactate`, should be `FIREAC.AntiSpectate`

• `fire-config` Spelling mistake → `FIREAC.AntiInvisble` should be `FIREAC.AntiInvisible`

• `fire-config` Spelling mistake → `FIREAC.MaxFootDistence` should be `FIREAC.MaxFootDistance`
• `fire-config` Spelling mistake → `FIREAC.MaxVehicleDistence` should be `FIREAC.MaxVehicleDistance`

• `fire-config` Spelling mistake → `FIREAC.AntiResourceStoper` should be `FIREAC.AntiResourceStopper`

• `fire-config` Spelling mistake → `FIREAC.SuiPunishment` should be `FIREAC.SuicidePunishment` (I'm serious)

• `fire-config` Grammar mistake → `FIREAC.AntiCollectedPickup` should be `FIREAC.AntiPickupCollect` (it looks better)
• `fire-config` Spelling mistake → `FIREAC.PickupePunishment` should be `FIREAC.PickupPunishment`

**Wrong Targeting**

• `Anti GM` targets a player that has opened a clothe shop (`fivem-appearance` from wasabi)
• `Anti TP` targets a player that was teleported by an admin (via ESX) from Mount Chilliad to LS

• `Anti TP` targets a player that is carried ("carry animation?") by another player which is a passenger in a moving car
The car was moving at `200kph`, the speed was achieved by boosting the engine via the `admin menu` from FIREAC

• `Anti AH` targets a player that... I don't know... is just a passenger in a moving car and looking around? [Image](https://cdn.discordapp.com/attachments/1045132884056473630/1046251013717364837/screenshot.png)

• A new player who joined the server was instantly triggering `Anti I` and then `Anti GM` after accessing the ped customization

• `Anti GM` also targets a player that's in tattoo menu (wasabi `fivem-appearance` again) [Image](https://cdn.discordapp.com/attachments/1045132884056473630/1046262707868942426/screenshot.png)

• `Anti SCH` targets passengers of a car of which driver is an admin that keeps changing the speed of the car
_Possible solution to this might be just skipping the target for passengers as I believe that passengers cannot_
_change the speed of the car (through cheats), only the driver can_ **Can't confirm this**

• `Anti SCH` targets a player that's just riding a motorcycle on a freeway or riding a car in the gang territories

**Bugs**

• `Noclip` cannot move to left or right (probably intended anyway)
• `Noclip` there's a rotation on moving backwards that does not happen every time

• Noclipping into a vehicle causes it to jump and get damaged, this shouldn't be happening

• Found out that it is possible to move to left and right in noclip, but it's also very slow and weird
Holding the `A` or `D` key and increasing the noclip speed will result in slowing down the movement speed of the admin

• Enabling `invisibility` and then noclip (both `Tx` and `FAC`) and
disabling the noclip after will result in the admin `being visible`

• Boosting a car and then fixing it results in the boost being lost

• Anti VPN blocks a player that doesn't use a vpn (different country, no vpn)

**Errors**

![image](https://user-images.githubusercontent.com/97387354/205121334-19fd8261-d6b7-44c4-b74a-8c0b84cd8e84.png)

![image](https://user-images.githubusercontent.com/97387354/206555638-d9f3a10c-b317-452c-9347-70dbcb73443a.png)

**Comment by Zzeyy** [comment]
Don't close this, check this every few hours. I'll keep this updated.

**Comment by Zzeyy** [comment]
Oh and perhaps you could pin my issues so it's always on top and more easy to access by both of us.

**Comment by AmIrReZa386** [comment]
I fix some bugs & I release it now .
`fivem-appearance` have some net glitch and this problem you wrote, not FIREAC bug
for example you can disconnect your internet in the shop then press back button (now you god mode) after that connect your internet
