### ISSUE TITLE
Discord Screenshot dos not have any exports

### ISSUE THREAD

**Issue by BlutwurstPro** [AmIrReZa386/FIREAC#25]
Hey,
discord-screenshot has no exports so requestCustomClientScreenshotUploadToDiscord dosent work

```console
@FIREAC/src/fire-server.lua:1866: No such export requestCustomClientScreenshotUploadToDiscord in resource discord-screenshot
```

**Comment by AmIrReZa386** [comment]
> Hey, discord-screenshot has no exports so requestCustomClientScreenshotUploadToDiscord dosent work
> 
> ```
> @FIREAC/src/fire-server.lua:1866: No such export requestCustomClientScreenshotUploadToDiscord in resource discord-screenshot
> ```

you are not add requirement scripts in `server.cfg`
