### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by IamPatrikexe** [AmIrReZa386/FIREAC#27]
The server kicks me for this reason: Reliable network event overflow

and i got this error: 

[       script:FIREAC] FIREAC: Player IamPatrik.exe Disconnected ...  |  Reason : (Reliable network event overflow.)
[       script:FIREAC] SCRIPT ERROR: @FIREAC/src/fire-server.lua:929: table index is nil
[       script:FIREAC] > handler (@FIREAC/src/fire-server.lua:929)

**Comment by IamPatrikexe** [comment]
@AmIrReZa386

**Comment by primoixi** [comment]
DO YOU KNOW WHICH KEY SHOULD I OUT IN ADMIN MENU 
FIREAC.AdminMenu = {
    Enable         = true,
    Key            = "INSERT",
    MenuPunishment = "BAN",
}

**Comment by AmIrReZa386** [comment]
this is not our anti cheat problem
some scripts spam events

> The server kicks me for this reason: Reliable network event overflow
> 
> and i got this error:
> 
> [ script:FIREAC] FIREAC: Player IamPatrik.exe Disconnected ... | Reason : (Reliable network event overflow.) [ script:FIREAC] SCRIPT ERROR: @FIREAC/src/fire-server.lua:929: table index is nil [ script:FIREAC] > handler (@FIREAC/src/fire-server.lua:929)
