### ISSUE TITLE
 Error: Loop svMain seems hung!

### ISSUE THREAD

**Issue by ShyoPedia** [AmIrReZa386/FIREAC#28]
[              server] Error: Loop svMain seems hung! (last checkin 45 seconds ago)
[              server] Warning: svMain watchdog stack: root
[              server] Error: Loop svMain STILL seems hung! (last checkin 90 seconds ago)
[              server] Warning: svMain watchdog stack: root

**Comment by primoixi** [comment]
DO YOU KNOW WHICH KEY SHOULD I OUT IN ADMIN MENU 
FIREAC.AdminMenu = {
    Enable         = true,
    Key            = "INSERT",
    MenuPunishment = "BAN",
}
