### ISSUE TITLE
Permissions & Bypass for resource source code

### ISSUE THREAD

**Issue by evilstriker** [AmIrReZa386/FIREAC#29]
~ I have added the ability to add / remove a temporary bypass using client events. For example: when joined bypass enabled and when loaded bypass disabled. Maybe you want to take this into your release or do you already have the ability to make bypass exceptions?

**Comment by AmIrReZa386** [comment]
Hi @evilstriker,

I will check it , thanks for report that !🙏

**Comment by evilstriker** [comment]
Sounds good I have added a server event called "anticheat:tempbypass" with a bool. And I have added a bool variable called "isBypassEnabled" in the fire-server.lua and added them to all the ban triggers / message triggers in a if statement.

You can now add the created event to your resources and give player a temporary bypass for example upon joining the server and loading in without getting a "Anti-Invisible" or "Anti-Teleport" ban.

**Comment by evilstriker** [comment]
Sounds good I have added a server event called "anticheat:tempbypass" with a bool. And I have added a bool variable called "isBypassEnabled" in the fire-server.lua and added them to all the ban triggers / message triggers in a if statement.

You can now add the created event to your resources and give player a temporary bypass for example upon joining the server and loading in without getting a "Anti-Invisible" or "Anti-Teleport" ban.

**Comment by evilstriker** [comment]
Sounds good I have added a server event called "anticheat:tempbypass" with a bool. And I have added a bool variable called "isBypassEnabled" in the fire-server.lua and added them to all the ban triggers / message triggers in a if statement.

You can now add the created event to your resources and give player a temporary bypass for example upon joining the server and loading in without getting a "Anti-Invisible" or "Anti-Teleport" ban.
