### ISSUE TITLE
FIREAC.AntiSpamVehicle , AntiSpamPed,AntiSpamObject settings does not work in version 6.1.7

### ISSUE THREAD

**Issue by RAXIC7** [AmIrReZa386/FIREAC#30]
FIREAC.AntiSpamVehicle , AntiSpamPed,AntiSpamObject settings does not work in version 6.1.7 

And Entity Settings Dont work ...

and errors

[       script:FIREAC] SCRIPT ERROR: @FIREAC/src/fire-server.lua:629: bad argument #1 to 'gsub' (string expected, got nil)
[       script:FIREAC] > handler (@FIREAC/src/fire-server.lua:629)

**Comment by AmIrReZa386** [comment]
Hi @RAXIC7 ,

Thanks for report it, I will check that 🙏

**Comment by AmIrReZa386** [comment]
No problem find in spam entity code
