### ISSUE TITLE
We banished even while being staff

### ISSUE THREAD

**Issue by theo-audureau** [AmIrReZa386/FIREAC#31]
I was banned by activating the no-clip even though I am superadmin

**Comment by RevolutionNetworks** [comment]
I dont have a Fix for the Code. But in the fire-white.lua use the [steam](steam:xxxxxxxxxxxxxx) That worked for me.

**Comment by AmIrReZa386** [comment]
Hi @theo-audureau,
[Check This Image](![image](https://user-images.githubusercontent.com/83431690/215049746-b2290971-13b2-45a3-957f-ab0c06ab710f.png))

**Comment by Baba1408** [comment]
Hello, I have the same problem, which image are you talking about?
