### ISSUE TITLE
Found someone who uses your script to sell in an abo... 

### ISSUE THREAD

**Issue by GGGd1n0** [AmIrReZa386/FIREAC#33]
Hi there, 
I found out that the guys from shakeshield are obviously using your script to sell it. I think your work is great and respect for offer it for free. But I hate such guys who are earning money with someones work. 
Sorry for writing it down here, but i think this is the fastest way to contact you. 
here are some links to their contact. 
https://shaketank.de/
https://discord.gg/XWEempKtEh
and the discord ID of its owner 661622207071518747

**Comment by Zzeyy** [comment]
That website is so ugly.

**Comment by AmIrReZa386** [comment]
Hi @GGGd1n0,
Thanks for your report !
I report them on https://support.discord.com/

**Comment by Zzeyy** [comment]
Even the video showcase isn't loading.

**Comment by AmIrReZa386** [comment]
I know some users copy & paste my code
I planned for new anti cheat
don't worry
