### ISSUE TITLE
(Idea) Raycasting Coords

### ISSUE THREAD

**Issue by Zzeyy** [AmIrReZa386/FIREAC#35]
Add a raycast that tells you the coords of where you're looking at.
Could be useful.

**Comment by AmIrReZa386** [comment]
Hi @Zzeyy,
FiveM doesn't have get coords of player camera .

**Comment by Zzeyy** [comment]
This feature is possible, though.

**Comment by Zzeyy** [comment]
Take inspiration from the RayCastCoords script.

**Comment by nutria22** [comment]
https://docs.fivem.net/natives/?_0x377906D8A31E5586
local player = PlayerPedId()
local playerCoords = GetEntityCoords(player)
local raycast = StartExpensiveSynchronousShapeTestLosProbe(playerCoords.x, playerCoords.y, playerCoords.z, GetOffsetFromEntityInWorldCoords(player, 0.0, 100.0, 0.0), 10, player, 0)
local _, _, _, _, result = GetShapeTestResult(raycast)
if result ~= nil then
    local hitCoords = _0x377906D8A31E5586(result)
    print("Hit coordinates: " .. hitCoords.x .. ", " .. hitCoords.y .. ", " .. hitCoords.z)
else
    print("Raycast did not hit anything.")
end

**Comment by Zzeyy** [comment]
> https://docs.fivem.net/natives/?_0x377906D8A31E5586 local player = PlayerPedId() local playerCoords = GetEntityCoords(player) local raycast = StartExpensiveSynchronousShapeTestLosProbe(playerCoords.x, playerCoords.y, playerCoords.z, GetOffsetFromEntityInWorldCoords(player, 0.0, 100.0, 0.0), 10, player, 0) local _, _, _, _, result = GetShapeTestResult(raycast) if result ~= nil then local hitCoords = _0x377906D8A31E5586(result) print("Hit coordinates: " .. hitCoords.x .. ", " .. hitCoords.y .. ", " .. hitCoords.z) else print("Raycast did not hit anything.") end

A little bit of formatting couldn't hurt.
But yeah, something like this.

**Comment by Zzeyy** [comment]
Also instead of printing the coordinates make it copy them.

**Comment by nutria22** [comment]
send me your discord

**Comment by nutria22** [comment]
add me Alexita#1234

**Comment by AmIrReZa386** [comment]
> 

I work on that and test it
not bad idea

**Comment by AmIrReZa386** [comment]
I tested this but nothing good option for anti cheat in this code
I don't have any good idea for this code
