### ISSUE TITLE
Issue report

### ISSUE THREAD

**Issue by MrHarebug** [AmIrReZa386/FIREAC#37]
Hello.
Some of think what your anticheat may block (I get him from your list on github) didnt work correctly.

---
All of this "Protected" I have enabled in config.
Anti Health Hack - Bypassed
Anti Infinity Ammo - Bypassed 
Anti Spactate - Bypassed
Anti Aim Assist - Bypassed (Not sure how this works)
Anti Aim Bot - Bypassed
Anti Noclip - Bypassed
Anti Teleport Vehicle - Bypassed
Anti Change Speed - Bypassed (Also Swim Speed)
Anti Weapon Damage Changer - Bypassed

Thats all for now.
Thanks for reading ^^

**Comment by MrHarebug** [comment]
Some new bugs what I found:
Restart resource from TX or from Web cause flag whole server as "Trying to stop resource"
Blow up gas station for example with car cause Flag "Spam Explosion"
Noclip flag work only if player have also invisible.. script noclip is ignored
AntiPedChanger target player who creating character from menu - default esx

Implement to update config with check time. Now every event is in one Thread with 5s delay. For example if someone give themself gun have ~5s to fire without been flagged. I think some of protection is better to set to lowest check time then other.

**Comment by Zzeyy** [comment]
> 

Can confirm the second and third
