### ISSUE TITLE
Another wrong trigger of anti godmode

### ISSUE THREAD

**Issue by Zzeyy** [AmIrReZa386/FIREAC#39]
Way to achieve this

- Kill a player with a knife
- Before the health is actually "removed" revive the player
- Anti godmode is triggered and the player is banned

Now, I'm aware this shouldn't happen during normal gameplay, but admins tend to have fun sometimes.

**Comment by Zzeyy** [comment]
This is actually also pretty hard to get. The timing must be near perfect.

**Comment by iSentrie** [comment]
huh, have you tried whitelisting admins? 😅

**Comment by Zzeyy** [comment]
> huh, have you tried whitelisting admins? 😅

That would be very helpful, especially when the player that's triggering the anti god mode is not an admin.

**Comment by AmIrReZa386** [comment]
I changed system of god mode thanks for reporting
