### ISSUE TITLE
I can fix it a! give me push access !

### ISSUE THREAD

**Issue by xxoptikxx** [AmIrReZa386/FIREAC#4]
I can fix it a! give me push access !

_Originally posted by @subhampro in https://github.com/AmIrReZa386/FIREAC/issues/3#issuecomment-1174622619_

Pls help me and i cant use the menu

**Comment by Katfer12** [comment]
Hi, I have installed this AC, but I have 3 problems, he constantly warns people for anti spawn ped, anti teleport and another person he threw anti godmode, On the other hand when I load the admin it detects them, but only 1 person gets the admin message and Allows you to open the menu. Sorry if I write to you here, do you have it working? sorry if i write to you but the owner dont answer, i want to see if it can be solved, can you help plis?
