### ISSUE TITLE
Spam filter doesn't work with chat scripts

### ISSUE THREAD

**Issue by Zzeyy** [AmIrReZa386/FIREAC#43]
![image](https://user-images.githubusercontent.com/97387354/215757740-b067cc13-a3ef-4d2c-b91d-c6549e92d545.png)

It does warn me for spamming commands, but not typing in chat. The resource used is okokChatV2.

**Comment by AmIrReZa386** [comment]
I will check it on okokChat

**Comment by Zzeyy** [comment]
> I will check it on okokChat

Are you actually gonna pay for the script or what? 😂

**Comment by Zzeyy** [comment]
I can borrow you a key

**Comment by Zzeyy** [comment]
@AmIrReZa386

**Comment by AmIrReZa386** [comment]
> 

This is not for spamming command
This is for spam in chat
if you spam **a**
for 2 time in 1 sec
you will warn fast
