### ISSUE TITLE
This level of engine boost doesn't do anything

### ISSUE THREAD

**Issue by Zzeyy** [AmIrReZa386/FIREAC#44]
![image](https://user-images.githubusercontent.com/97387354/215761238-80f0f9b2-e81c-4dc2-ad7a-852b45fa67b7.png)

This level does not change speed at all, need to use level 2 instead, which is pretty fast.

**Comment by AmIrReZa386** [comment]
Yes this is for another thing 😂
It's soo crazy option

**Comment by AmIrReZa386** [comment]
I fixed on new version
