### ISSUE TITLE
Anti VPN being goofy

### ISSUE THREAD

**Issue by Zzeyy** [AmIrReZa386/FIREAC#47]

**Comment by Zzeyy** [comment]
![image](https://user-images.githubusercontent.com/97387354/216352415-f7eb12f5-bba0-4c39-be76-d77e79f04492.png)

Anyone with a dynamic IP address will get targeted after their IP changes.

**Comment by Zzeyy** [comment]
The goofy thing is that only the last number changed.

**Comment by AmIrReZa386** [comment]
> The goofy thing is that only the last number changed.

You know when you are use VPN
your ip change to vpn server
and vpn server is very easy for detect
this [website](https://ip-api.com/) detect your server type when you connect
i can't do anything for that
