### ISSUE TITLE
Add anti Eulen

### ISSUE THREAD

**Issue by liam16361** [AmIrReZa386/FIREAC#49]
Dectects, eulen and redengine

**Comment by iSentrie** [comment]
? :D

**Comment by Zzeyy** [comment]
@liam16361 You think it's so easy, right?

**Comment by Zzeyy** [comment]
Like writing `if eulen then ban`, hm?

**Comment by AmIrReZa386** [comment]
> Like writing `if eulen then ban`, hm?

yes like this :
```
if eulen == true then
FIREAC Ban him
end
```
😂😂😂😂😂😂😂
