### ISSUE TITLE
THIS NEEDS YOUR ATTENTION (Health bug)

### ISSUE THREAD

**Issue by Zzeyy** [AmIrReZa386/FIREAC#51]
With FIREAC loaded, players keep losing health.
When FIREAC is unloaded, players don't lose health anymore.

This can lead to a death, some players have died at once, including me when in spectate.

https://medal.tv/games/gta-v/clips/V4gPqmbuzA65n/d1337i2KedIp?invite=cr-MSw3WWQsNjEzODE3Njgs
Keep attention on the health indicator

**Comment by Zzeyy** [comment]
Most often it's just subtracting two points and then returning it.
But sometimes it bugs out and players will keep losing health, 2 points per second (death in 50 seconds).

**Comment by Zzeyy** [comment]
![image](https://user-images.githubusercontent.com/97387354/218781245-c171b10f-7565-49be-8252-83d172151125.png)
I've been standing still under the map in one place for around two hours

**Comment by Zzeyy** [comment]
I don't know if it can be done on the AC side,
but making it so the godmode check is not detected by log scripts, such as JD_logs, would be awesome.

**Comment by AmIrReZa386** [comment]
I change anti cheat god mode code
it's not good
✅

**Comment by AmIrReZa386** [comment]
I fixed on new version
thanks for reporting
