### ISSUE TITLE
TxAdmin Admins get banned

### ISSUE THREAD

**Issue by RedDragonElite** [AmIrReZa386/FIREAC#53]
If i use stuff from TxAdmin i get banned xD how to bypass admins ^^

**Comment by AmIrReZa386** [comment]
> If i use stuff from TxAdmin i get banned xD how to bypass admins ^^

You need to put admin identifiers in [fire-white.lua](https://github.com/AmIrReZa386/FIREAC/blob/main/whitelists/fire-white.lua)

**Comment by RedDragonElite** [comment]
thx
