### ISSUE TITLE
Problem with the deferrals

### ISSUE THREAD

**Issue by daanigann** [AmIrReZa386/FIREAC#54]
When a user joins the server a problems shows up when another script with deferrals try's to put a message, in this case is the "Steam is closed." from the bwh.

[recording-2023-03-06-19-58-55.webm](https://user-images.githubusercontent.com/117041487/223205320-4643cefd-4463-4ed6-a21b-b451c37d9079.webm)

**Comment by AmIrReZa386** [comment]
This is not our anti cheat problem
