### ISSUE TITLE
i have an bug when someone is getting detected by the anticheat nobody can connect

### ISSUE THREAD

**Issue by gabrieltr0008** [AmIrReZa386/FIREAC#56]
so if someone gets detected, then nobody can join, when joining it says "FIREAC: Deferring Connection"

**Comment by AmIrReZa386** [comment]
This is your server problem with player connection
This problem is not side of anti-cheat

**Comment by gabrieltr0008** [comment]
> This is your server problem with player connection
> This problem is not side of anti-cheat

No, it started when I updated the anticheat. With your old anticheat version it works fine. Only with the newest you released few days ago

**Comment by AmIrReZa386** [comment]
> > This is your server problem with player connection
> > This problem is not side of anti-cheat
> 
> No, it started when I updated the anticheat. With your old anticheat version it works fine. Only with the newest you released few days ago

Do you have discord ?

**Comment by gabrieltr0008** [comment]
Yes

**Comment by AmIrReZa386** [comment]
Can you open a ticket in FIREAC discord ?

**Comment by gabrieltr0008** [comment]
Ok
