### ISSUE TITLE
Banned

### ISSUE THREAD

**Issue by Paul0725** [AmIrReZa386/FIREAC#8]
Can you help me unbanned Anti Resources Stopper because i didn't do anything i just changing my mask at mask shop and i get banned how can i fix it i have no idea why i'm ban
![image](https://user-images.githubusercontent.com/116023523/196240376-cced60b4-1509-4fbb-99ef-caf77422735a.png)

**Comment by AmIrReZa386** [comment]
What is your Ban Details ?
