### ISSUE TITLE
Anti Inject not working, and many false cheats

### ISSUE THREAD

**Issue by ChickenDipper1** [AmIrReZa386/FIREAC#9]
The command: /fire install [fx] does not work, says it does not exist. How can I install anti inject please?

I also get hundreds or ped spawn and vehicle spawn warnings when I spawn into my server, why would this be happening please?

**Comment by AmIrReZa386** [comment]
Do you have npc in your server ?

**Comment by AmIrReZa386** [comment]
Hi @ChickenDipper1,

`fire install [fx]` command removed very past
I update spawn entity event for server have NPC
users don't have problem with NPC now

Thanks, Amirreza Jaberi
